subdir-ccflags-y += \
    -I$(srctree)/techpack/video-driver/driver/vidc/inc \
    -I$(srctree)/techpack/video-driver/driver/platform/common/inc \
    -I$(srctree)/techpack/video-driver/include/uapi/vidc \
    -I$(srctree)/techpack/video-driver/include/uapi/vidc/media

#obj-y += msm_video.o

#msm_video-objs += driver/vidc/src/msm_vidc_v4l2.o \
#                  driver/vidc/src/msm_vidc_vb2.o \
#                  driver/vidc/src/msm_vidc.o \
#                  driver/vidc/src/msm_vdec.o \
#                  driver/vidc/src/msm_venc.o \
#                  driver/vidc/src/msm_vidc_driver.o \
#                  driver/vidc/src/msm_vidc_control.o \
#                  driver/vidc/src/msm_vidc_buffer.o \
#                  driver/vidc/src/msm_vidc_power.o \
#                  driver/vidc/src/msm_vidc_probe.o \
#                  driver/vidc/src/msm_vidc_dt.o \
#                  driver/vidc/src/msm_vidc_debug.o \
#                  driver/vidc/src/msm_vidc_memory.o \
#                  driver/vidc/src/msm_vidc_fence.o \
#                  driver/vidc/src/venus_hfi.o \
#                  driver/vidc/src/hfi_packet.o \
#                  driver/vidc/src/venus_hfi_response.o \
#                  driver/platform/common/src/msm_vidc_platform.o