LINUXINCLUDE    += -I$(VIDEO_ROOT)/driver/vidc/inc \
                   -I$(VIDEO_ROOT)/driver/platform/common/inc \
                   -I$(VIDEO_ROOT)/include/uapi/vidc

USERINCLUDE     += -I$(VIDEO_ROOT)/include/uapi/vidc/media \
                   -I$(VIDEO_ROOT)/include/uapi/vidc

obj-y += msm_video.o

msm_video-objs += driver/vidc/src/msm_vidc_v4l2.o \
                  driver/vidc/src/msm_vidc_vb2.o \
                  driver/vidc/src/msm_vidc.o \
                  driver/vidc/src/msm_vdec.o \
                  driver/vidc/src/msm_venc.o \
                  driver/vidc/src/msm_vidc_driver.o \
                  driver/vidc/src/msm_vidc_control.o \
                  driver/vidc/src/msm_vidc_buffer.o \
                  driver/vidc/src/msm_vidc_power.o \
                  driver/vidc/src/msm_vidc_probe.o \
                  driver/vidc/src/msm_vidc_dt.o \
                  driver/vidc/src/msm_vidc_debug.o \
                  driver/vidc/src/msm_vidc_memory.o \
                  driver/vidc/src/msm_vidc_fence.o \
                  driver/vidc/src/venus_hfi.o \
                  driver/vidc/src/hfi_packet.o \
                  driver/vidc/src/venus_hfi_response.o \
                  driver/platform/common/src/msm_vidc_platform.o