#KBUILD_OPTIONS+= VIDEO_ROOT=$(KERNEL_SRC)/$(M)
#KBUILD_OPTIONS += KBUILD_EXTRA_SYMBOLS=$(OUT_DIR)/../sm8450-modules/qcom/opensource/mmrm-driver/Module.symvers

#all:
#	$(MAKE) -C $(KERNEL_SRC) M=$(M) modules $(KBUILD_OPTIONS)

#%:
#	$(MAKE) -C $(KERNEL_SRC) M=$(M) $@ $(KBUILD_OPTIONS)

#clean:
#	rm -f *.o *.ko *.mod.c *.mod.o *~ .*.cmd Module.symvers
#	rm -rf .tmp_versions